# Generated by Django 5.2.4 on 2025-07-23 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address_line_1_customuser_address_line_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state_province',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='zip_postal_code',
        ),
    ]
