# Generated by Django 5.2.4 on 2025-07-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_address_postal_code_alter_address_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(max_length=128, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'address_line_1', 'address_line_2', 'city', 'state', 'postal_code', 'country')},
        ),
    ]
